Pinguin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reg_auth/', include('reg_auth.urls')),
]

reg_auth/urls.py
from django.urls import path, include

from . import views


app_name = 'reg_auth'
urlpatterns = [
    path('', views.reg_auth, name='reg_auth'),
    path('registration/', views.registration, name='registration'),
    path('authentication/', views.authentication, name='authentication'),
    path('<email>/<key>/', views.confirm_email, name='confirm_email'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
]

reg_auth/models.py
from django.db import models


class UserData(models.Model):
    username = models.CharField(max_length=24, blank=True, null=True)
    email = models.EmailField(max_length=32)
    password = models.CharField(max_length=32)
    created_data = models.DateTimeField()
    email_confirm_key = models.CharField(max_length=20, blank=True, null=True)
    remember_me = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return "Email: {}, Data: {}.".format(self.email, self.created_data)

    class Meta:
        verbose_name = "Данные пользователя"
        verbose_name_plural = "Данные пользователей"

reg_auth/forms.py
from django import forms

from .models import UserData


class SignUpForm(forms.Form):
    email = forms.CharField(required=True, error_messages={'required': 'Укажите Email'})
    email_validate = forms.CharField()
    password = forms.CharField(required=True, error_messages={'required': 'Укажите пароль'})
    password_validate = forms.CharField()
    confirm_password = forms.CharField(required=True, error_messages={'required': 'Повторите пароль'})
    confirm_password_validate = forms.CharField()

    def clean(self):

        email = str(self.cleaned_data.get('email'))
        email_validate = str(self.cleaned_data.get('email_validate'))
        password_validate = str(self.cleaned_data.get('password_validate'))
        confirm_password_validate = str(self.cleaned_data.get('confirm_password_validate'))

        if email_validate == 'no_validate':
            raise forms.ValidationError('Не допустимый Email!')

        if password_validate == 'no_validate':
            raise forms.ValidationError('Простой пароль!')

        if confirm_password_validate == 'no_validate':
            raise forms.ValidationError('Пароли не совпадают!')

        # Проверка совпадения имени
        try:
            user = UserData.objects.get(email=email)
            raise forms.ValidationError('Пользователь с данным Email уже зарегистрирован!')
        except UserData.DoesNotExist:
            pass

        return self.cleaned_data


class SignInForm(forms.Form):
    email = forms.CharField(required=True, error_messages={'required': 'Укажите Email'})
    password = forms.CharField(required=True, error_messages={'required': 'Укажите пароль'})
    remember_me = forms.BooleanField(required=False)

    def clean(self):

        email = str(self.cleaned_data.get('email'))
        password = str(self.cleaned_data.get('password'))

        # Проверка совпадения имени
        try:
            user = UserData.objects.get(email=email)
            print(password)
            print(user.password)
            print(password != user.password)
            if password != user.password:
                raise forms.ValidationError('Не правильный пароль!', code='password_error')
        except UserData.DoesNotExist:
            raise forms.ValidationError('Данный Email не зарегистрирован!', code='email_error')

        return self.cleaned_data

reg_auth/views.py
from django.shortcuts import render
from datetime import datetime
from django.core.mail import EmailMessage

from . import special_func
from .models import UserData
from .forms import SignUpForm, SignInForm


def reg_auth(request):
    signup_form = SignUpForm()
    signin_form = SignInForm()
    is_auth = True
    return render(request, 'reg_auth/index.html', locals())


def registration(request):
    signup_form = SignUpForm()

    if request.method == 'POST':
        signup_form = SignUpForm(request.POST or None)

        data = request.POST
        is_create_user = False

        if signup_form.is_valid():

            email = data['email']
            password = data['password']
            confirm_password = data['confirm_password']

            key = special_func.generate_key()
            user = UserData.objects.create(email=email, password=password, created_data=datetime.now(),
                                           email_confirm_key=key)

            email = EmailMessage('Confirm email Pinguin', 'Hello! Thank you for registering!\n '
                                'Confirm your email: http://127.0.0.1:8033/reg_auth/{}/{}'.format(email, key),
                                to = [email])
            email.send()

            is_create_user = True

        else:

            print(data['email_validate'])
            if data['email_validate'] == 'validate':
                email = data['email']

            if data['password_validate'] == 'validate':
                password = data['password']

            if data['confirm_password_validate'] == 'validate':
                confirm_password = data['confirm_password']

    return render(request, 'reg_auth/index.html', locals())


def confirm_email(request, email, key):
    user = UserData.objects.get(email=email)

    if user.email_confirm_key == key:
        user.email_confirm_key = None #email подтверждён
        user.save()

    return render(request, 'user_page.html', locals())


def authentication(request):
    signin_form = SignInForm()
    is_auth = True

    if request.method == 'POST':
        signin_form = SignInForm(request.POST or None)

        data = request.POST
        email = data['email']

        if signin_form.is_valid():
            user = UserData.objects.get(email=email)
            return render(request, 'user_page.html', locals())
        else:
            is_auth = False
            error_code = signin_form.errors['__all__'].as_data()[0].code

    return render(request, 'reg_auth/index.html', locals())

def forgot_password(request):

    return render(request, 'reg_auth/index.html', locals())

templates/reg_auth/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pinguin</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'img/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="keywords" content="">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick-theme.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=cyrillic" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'reg_auth/css/reg_auth.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'reg_auth/css/modal_windows.css' %}" type="text/css">

    <script defer src="{% static 'fontawesome-free-5.0.8/svg-with-js/js/fontawesome-all.js' %}"></script>

</head>
<body>

<div class="main-wrapper">

        <div class="left-half">

            <div class="slider">

                <div class="slide">
                    <div class="slide-img">
                        <img src="{% static 'img/Get_support.png' %}">
                    </div>
                    <div class="slide-text">
                        <h3>Get support</h3>
                        <p>Welcome to <b>Pinguin</b> a safe place to share how you fell</p>
                    </div>
                </div>

                <div class="slide">
                    <div class="slide-img">
                        <img src="{% static 'img/Chat_with_friends.png' %}">
                    </div>
                    <div class="slide-text">
                        <h3>Chat with friends</h3>
                        <p>Welcome to <b>Pinguin</b> a quiet pace to communicate</p>
                    </div>
                </div>

                <div class="slide">
                    <div class="slide-img">
                        <img src="{% static 'img/Spread_love.png' %}">
                    </div>
                    <div class="slide-text">
                        <h3>Spread love</h3>
                        <p>Welcome to <b>Pinguin</b> a wonderful place to find your one and only</p>
                    </div>
                </div>

            </div><!--carousel-wrapper-->

        </div><!--left-half-->

        <div class="right-half">

            <div class="logo">
                Pinguin<img src="{% static 'img/penguin.png' %}">
            </div>

            <div class="reg-auth-block">

                <ul class="nav-forms">
                    <li id="signin_btn"><a>SIGN IN</a></li>
                    <li id="signup_btn"><a>SIGN UP</a></li>
                    <span id="menu_underline"></span>
                </ul>

                <form class="form-main form-signin" action="{% url 'reg_auth:authentication' %}" method="post">{% csrf_token %}

                    <div class="field-wrapper">
                        <label>Email</label>
                        <input id="in_signin_email" type="text" name="{{ signin_form.email.html_name }}"  required autocomplete="off" value="{{ email }}">
                        <span class="check-icon"><i class="fas fa-check"></i></span>
                    </div>

                    <div class="field-wrapper">
                        <label>Password</label>
                        <input id="in_signin_password" type="password" name="{{ signin_form.password.html_name }}" required autocomplete="off">
                        <span class="check-icon"><i class="fas fa-check"></i></span>
                    </div>

                    <div class="field-wrapper-checkbox">
                        <input id="in_signin_checkbox" class="input-checkbox" type="checkbox" name="{{ signin_form.remember_me.html_name }}">
                        <label class="label-checkbox" for="input_checkbox1">Keep my Signed In</label>
                    </div>

                    <div class="field-wrapper">
                        <button class="btn-submit-form" type="submit">SIGN IN</button>
                        <div class="form_error_main">{{ signin_form.errors }}</div>
                        <div class="form_error">{{ signin_form.errors }}</div>
                    </div>

                    <hr id="line">

                    <div class="forgot-password">
                        <a href="{% url 'reg_auth:reg_auth' %}">Forgot password?</a>
                    </div>

                </form>

                <form class="form-main form-signup" action="{% url 'reg_auth:registration' %}" method="post">{% csrf_token %}

                    <div class="field-wrapper">
                        <label>Email</label>
                        <input id="in_signup_email" type="text" name="{{ signup_form.email.html_name }}" required autocomplete="off" value="{{ email }}">
                        <span class="check-icon"><i class="fas fa-check"></i></span>
                        <input class="input-validate" id="signup_email_validate" type="text" value="no_validate" name="{{ signup_form.email_validate.html_name }}">
                    </div>

                    <div class="field-wrapper">
                        <label>Password</label>
                        <input id="in_signup_password" type="password" name="{{ signup_form.password.html_name }}" required autocomplete="off" value="{{ password }}">
                        <span class="check-icon"><i class="fas fa-check"></i></span>
                        <input class="input-validate" id="signup_password_validate" type="text" value="no_validate" name="{{ signup_form.password_validate.html_name }}">
                    </div>

                    <div class="field-wrapper">
                        <label>Confirm password</label>
                        <input id="in_signup_con_password" type="password" name="{{ signup_form.confirm_password.html_name }}" required autocomplete="off" value="{{ confirm_password }}">
                        <span class="check-icon"><i class="fas fa-check"></i></span>
                        <input class="input-validate" id="signup_confirm_password_validate" type="text" value="no_validate" name="{{ signup_form.confirm_password_validate.html_name }}">
                    </div>

                    <div class="field-wrapper">
                        <button class="btn-submit-form" type="submit">SIGN UP</button>
                        <div class="form_error_main">{{ signup_form.errors }}</div>
                        <div class="form_error">{{ signup_form.errors }}</div>
                    </div>

                </form>

            </div><!--reg-auth-block-->

        </div>

        </div><!--right-half-->

</div><!--main-wrapper-->

<!--modal-forms-->
{% if is_create_user %}
<div class="modal-form" id="modal_confirmation_email">
    <span class="modal-close"><i class="fas fa-times"></i></span>
    <p>
        <h4>Спасибо за регистрацию!</h4>
        Проверьте пожалуйста свою почту для подтверждения Email.
    </p>
</div>
<div class="overlay"></div>
{% endif %}

<script src="{% static 'js/jquery-3.2.1.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/slick.min.js' %}" type="text/javascript"></script>
<script src="{% static 'reg_auth/js/reg_auth.js' %}" type="text/javascript"></script>
<script src="{% static 'reg_auth/js/modal_windows.js' %}" type="text/javascript"></script>
{% if is_create_user %}
<script src="{% static 'reg_auth/js/clear_form.js' %}" type="text/javascript"></script>
{% endif %}
{% if not is_auth %}
<script src="{% static 'reg_auth/js/not_auth.js' %}" type="text/javascript"></script>
{% endif %}
{% if error_code == 'email_error' %}
<script src="{% static 'reg_auth/js/clear_email_field.js' %}" type="text/javascript"></script>
{% endif %}

</body>
</html>

templates/user_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My page</title>
</head>
<body>
<h1>This is page user's {{ user.email}} with id{{ user.id }}</h1>
</body>
</html>